#!/usr/bin/env python3
# -*- coding: CP1252 -*-
#
# generated by wxGlade 1.0.4 on Wed Nov  9 14:30:59 2022
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from main_aquasearch import main_aquasearch


class MyApp(wx.App):
    def OnInit(self):
        self.Aquasearch = main_aquasearch(None, wx.ID_ANY, "")
        self.SetTopWindow(self.Aquasearch)
        self.Aquasearch.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
