# -*- coding: CP1252 -*-
#
# generated by wxGlade 1.0.4 on Mon Oct 17 11:05:10 2022
#

import wx
import wx.lib.filebrowsebutton as filebrowse
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1000, 600))
        self.SetTitle("Aquasearch")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("Icon.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)

        self.notebook_1 = wx.Notebook(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)

        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1_pane_1.SetBackgroundColour(wx.Colour(188, 188, 188))
        self.notebook_1.AddPage(self.notebook_1_pane_1, "New query")

        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        self.panel_2 = wx.Panel(self.notebook_1_pane_1, wx.ID_ANY, style=wx.CLIP_CHILDREN | wx.FULL_REPAINT_ON_RESIZE)
        self.panel_2.SetMinSize((1000, 35))
        self.panel_2.SetBackgroundColour(wx.Colour(252, 255, 116))
        sizer_2.Add(self.panel_2, 0, wx.ALL | wx.EXPAND, 5)

        sizer_5 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_2, wx.ID_ANY, "Welcome to Aquasearch", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_1.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_5.Add(label_1, 0, wx.BOTTOM | wx.EXPAND, 5)

        self.panel_3 = wx.Panel(self.notebook_1_pane_1, wx.ID_ANY, style=wx.CLIP_CHILDREN | wx.FULL_REPAINT_ON_RESIZE)
        self.panel_3.SetMinSize((1000, 35))
        self.panel_3.SetBackgroundColour(wx.Colour(0, 127, 255))
        sizer_2.Add(self.panel_3, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 5)

        sizer_6 = wx.BoxSizer(wx.VERTICAL)

        self.panel_12 = wx.Panel(self.panel_3, wx.ID_ANY)
        sizer_6.Add(self.panel_12, 1, wx.ALL | wx.EXPAND, 5)

        sizer_7 = wx.BoxSizer(wx.VERTICAL)

        self.button_1 = filebrowse.FileBrowseButton(self.panel_12, wx.ID_ANY, changeCallback = self.fbbCallback, dialogTitle= 'Import')
        sizer_7.Add(self.button_1, 0, wx.EXPAND, 0)

        self.panel_4 = wx.Panel(self.notebook_1_pane_1, wx.ID_ANY)
        sizer_2.Add(self.panel_4, 4, wx.EXPAND, 0)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_13 = wx.Panel(self.panel_4, wx.ID_ANY)
        self.panel_13.SetMinSize((200, -1))
        self.panel_13.SetBackgroundColour(wx.Colour(255, 168, 0))
        sizer_8.Add(self.panel_13, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 5)

        sizer_15 = wx.BoxSizer(wx.VERTICAL)

        self.panel_25 = wx.Panel(self.panel_13, wx.ID_ANY)
        self.panel_25.SetMinSize((-1, 50))
        sizer_15.Add(self.panel_25, 0, wx.EXPAND, 0)

        sizer_18 = wx.BoxSizer(wx.VERTICAL)

        label_3 = wx.StaticText(self.panel_25, wx.ID_ANY, "Parameters of the query", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_3.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_18.Add(label_3, 1, wx.EXPAND | wx.TOP, 7)

        self.panel_26 = wx.Panel(self.panel_13, wx.ID_ANY)
        self.panel_26.SetMinSize((-1, 50))
        sizer_15.Add(self.panel_26, 0, wx.EXPAND, 0)

        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_32 = wx.Panel(self.panel_26, wx.ID_ANY)
        sizer_19.Add(self.panel_32, 1, wx.EXPAND | wx.LEFT, 8)

        sizer_20 = wx.BoxSizer(wx.VERTICAL)

        label_4 = wx.StaticText(self.panel_32, wx.ID_ANY, "Tolerance")
        label_4.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_20.Add(label_4, 0, wx.ALIGN_RIGHT | wx.SHAPED, 0)

        self.panel_33 = wx.Panel(self.panel_26, wx.ID_ANY)
        sizer_19.Add(self.panel_33, 1, wx.EXPAND, 0)

        sizer_21 = wx.BoxSizer(wx.VERTICAL)

        self.spin_ctrl_double_1 = wx.SpinCtrlDouble(self.panel_33, wx.ID_ANY, initial=0.05, min=0.0, max=0.5, style=wx.ALIGN_CENTRE_HORIZONTAL | wx.SP_ARROW_KEYS)
        self.spin_ctrl_double_1.SetMinSize((-1, 25))
        self.spin_ctrl_double_1.SetIncrement(0.025)
        self.spin_ctrl_double_1.SetDigits(3)
        sizer_21.Add(self.spin_ctrl_double_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.SHAPED, 0)

        self.panel_27 = wx.Panel(self.panel_13, wx.ID_ANY)
        self.panel_27.SetMinSize((-1, 50))
        sizer_15.Add(self.panel_27, 0, wx.EXPAND, 0)

        sizer_22 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_34 = wx.Panel(self.panel_27, wx.ID_ANY)
        sizer_22.Add(self.panel_34, 1, wx.EXPAND | wx.LEFT, 8)

        sizer_23 = wx.BoxSizer(wx.VERTICAL)

        label_5 = wx.StaticText(self.panel_34, wx.ID_ANY, "mz power")
        label_5.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_23.Add(label_5, 0, wx.ALIGN_RIGHT | wx.SHAPED, 0)

        self.panel_35 = wx.Panel(self.panel_27, wx.ID_ANY)
        sizer_22.Add(self.panel_35, 1, wx.EXPAND, 0)

        sizer_24 = wx.BoxSizer(wx.VERTICAL)

        self.spin_ctrl_double_2 = wx.SpinCtrlDouble(self.panel_35, wx.ID_ANY, initial=0.0, min=0.0, max=5.0, style=wx.ALIGN_CENTRE_HORIZONTAL | wx.SP_ARROW_KEYS)
        self.spin_ctrl_double_2.SetMinSize((-1, 25))
        self.spin_ctrl_double_2.SetDigits(0)
        sizer_24.Add(self.spin_ctrl_double_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.SHAPED, 0)

        self.panel_28 = wx.Panel(self.panel_13, wx.ID_ANY)
        self.panel_28.SetMinSize((-1, 50))
        sizer_15.Add(self.panel_28, 0, wx.EXPAND, 0)

        sizer_25 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_36 = wx.Panel(self.panel_28, wx.ID_ANY)
        sizer_25.Add(self.panel_36, 1, wx.EXPAND | wx.LEFT, 8)

        sizer_26 = wx.BoxSizer(wx.VERTICAL)

        label_6 = wx.StaticText(self.panel_36, wx.ID_ANY, "Intensity power")
        label_6.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_26.Add(label_6, 0, wx.ALIGN_RIGHT | wx.SHAPED, 0)

        self.panel_37 = wx.Panel(self.panel_28, wx.ID_ANY)
        sizer_25.Add(self.panel_37, 1, wx.EXPAND, 0)

        sizer_27 = wx.BoxSizer(wx.VERTICAL)

        self.spin_ctrl_double_3 = wx.SpinCtrlDouble(self.panel_37, wx.ID_ANY, initial=1.0, min=0.0, max=5.0, style=wx.ALIGN_CENTRE_HORIZONTAL | wx.SP_ARROW_KEYS)
        self.spin_ctrl_double_3.SetMinSize((-1, 25))
        self.spin_ctrl_double_3.SetDigits(0)
        sizer_27.Add(self.spin_ctrl_double_3, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.SHAPED, 0)

        self.panel_29 = wx.Panel(self.panel_13, wx.ID_ANY)
        self.panel_29.SetMinSize((-1, 50))
        sizer_15.Add(self.panel_29, 0, wx.EXPAND, 0)

        sizer_28 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_38 = wx.Panel(self.panel_29, wx.ID_ANY)
        sizer_28.Add(self.panel_38, 1, wx.EXPAND | wx.LEFT, 8)

        sizer_29 = wx.BoxSizer(wx.VERTICAL)

        label_7 = wx.StaticText(self.panel_38, wx.ID_ANY, "Database")
        label_7.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_29.Add(label_7, 0, wx.ALIGN_RIGHT | wx.SHAPED, 0)

        self.panel_39 = wx.Panel(self.panel_29, wx.ID_ANY)
        sizer_28.Add(self.panel_39, 1, wx.EXPAND | wx.LEFT, 10)

        sizer_30 = wx.BoxSizer(wx.VERTICAL)

        self.combo_box_1 = wx.ComboBox(self.panel_39, wx.ID_ANY, choices=["Aquasearch_study"], style=wx.CB_DROPDOWN)
        sizer_30.Add(self.combo_box_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_30 = wx.Panel(self.panel_13, wx.ID_ANY)
        sizer_15.Add(self.panel_30, 2, wx.EXPAND, 0)

        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_6 = wx.Panel(self.panel_30, wx.ID_ANY)
        sizer_14.Add(self.panel_6, 1, wx.EXPAND, 0)

        self.panel_31 = wx.Panel(self.panel_13, wx.ID_ANY)
        sizer_15.Add(self.panel_31, 0, wx.ALIGN_RIGHT | wx.ALL | wx.EXPAND | wx.SHAPED, 5)

        sizer_16 = wx.BoxSizer(wx.VERTICAL)

        self.panel_5 = wx.Panel(self.panel_31, wx.ID_ANY)
        sizer_16.Add(self.panel_5, 0, wx.ALIGN_RIGHT | wx.EXPAND | wx.SHAPED, 0)

        sizer_31 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_20 = wx.Panel(self.panel_5, wx.ID_ANY)
        sizer_31.Add(self.panel_20, 1, wx.EXPAND, 0)

        self.button_2 = wx.Button(self.panel_5, wx.ID_ANY, "Run")
        self.button_2.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_31.Add(self.button_2, 0, wx.ALIGN_BOTTOM, 0)

        self.panel_14 = wx.Panel(self.panel_4, wx.ID_ANY)
        sizer_8.Add(self.panel_14, 1, wx.EXPAND, 0)

        sizer_32 = wx.BoxSizer(wx.VERTICAL)

        self.panel_21 = wx.Panel(self.panel_14, wx.ID_ANY, style=wx.BORDER_SUNKEN)
        self.panel_21.SetBackgroundColour(wx.Colour(255, 255, 255))
        sizer_32.Add(self.panel_21, 5, wx.BOTTOM | wx.EXPAND | wx.RIGHT, 5)

        sizer_33 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_22 = wx.Panel(self.panel_21, wx.ID_ANY, style=wx.BORDER_SIMPLE)
        sizer_33.Add(self.panel_22, 5, wx.EXPAND | wx.RIGHT, 0)

        sizer_34 = wx.BoxSizer(wx.VERTICAL)

        label_8 = wx.StaticText(self.panel_22, wx.ID_ANY, "Protein results")
        label_8.SetMinSize((187, 40))
        label_8.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_34.Add(label_8, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_24 = wx.Panel(self.panel_22, wx.ID_ANY)
        self.panel_24.SetBackgroundColour(wx.Colour(255, 255, 255))
        sizer_34.Add(self.panel_24, 1, wx.EXPAND, 0)

        self.panel_23 = wx.Panel(self.panel_21, wx.ID_ANY, style=wx.BORDER_SIMPLE)
        sizer_33.Add(self.panel_23, 7, wx.EXPAND, 0)

        sizer_35 = wx.BoxSizer(wx.VERTICAL)

        label_9 = wx.StaticText(self.panel_23, wx.ID_ANY, "Sample analysis")
        label_9.SetMinSize((187, 40))
        label_9.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_35.Add(label_9, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.SHAPED, 0)

        self.panel_40 = wx.Panel(self.panel_23, wx.ID_ANY)
        self.panel_40.SetBackgroundColour(wx.Colour(255, 255, 255))
        sizer_35.Add(self.panel_40, 1, wx.EXPAND, 0)

        self.panel_41 = wx.Panel(self.panel_23, wx.ID_ANY)
        self.panel_41.SetMinSize((465, 100))
        self.panel_41.SetBackgroundColour(wx.Colour(249, 249, 220))
        sizer_35.Add(self.panel_41, 0, wx.EXPAND, 0)

        sizer_36 = wx.BoxSizer(wx.HORIZONTAL)

        sizer_37 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_36.Add(sizer_37, 3, wx.EXPAND, 0)

        self.panel_44 = wx.Panel(self.panel_41, wx.ID_ANY, style=wx.BORDER_THEME)
        sizer_37.Add(self.panel_44, 3, wx.EXPAND, 0)

        sizer_38 = wx.BoxSizer(wx.VERTICAL)

        sizer_39 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_38.Add(sizer_39, 1, wx.EXPAND, 0)

        sizer_40 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_39.Add(sizer_40, 3, 0, 0)

        self.panel_50 = wx.Panel(self.panel_44, wx.ID_ANY)
        sizer_40.Add(self.panel_50, 3, wx.EXPAND, 0)

        sizer_45 = wx.BoxSizer(wx.HORIZONTAL)

        label_10 = wx.StaticText(self.panel_50, wx.ID_ANY, "Number of PCs")
        label_10.SetMinSize((93, 18))
        label_10.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_45.Add(label_10, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.SHAPED, 25)

        self.spin_ctrl_double_9 = wx.SpinCtrlDouble(self.panel_44, wx.ID_ANY, initial=0.0, min=0.0, max=5.0, style=wx.ALIGN_CENTRE_HORIZONTAL | wx.SP_ARROW_KEYS)
        self.spin_ctrl_double_9.SetDigits(0)
        sizer_40.Add(self.spin_ctrl_double_9, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 5)

        self.panel_47 = wx.Panel(self.panel_44, wx.ID_ANY)
        sizer_39.Add(self.panel_47, 1, wx.EXPAND, 0)

        sizer_41 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_38.Add(sizer_41, 1, wx.EXPAND, 0)

        sizer_42 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_41.Add(sizer_42, 3, 0, 0)

        self.panel_51 = wx.Panel(self.panel_44, wx.ID_ANY)
        sizer_42.Add(self.panel_51, 3, wx.EXPAND, 0)

        sizer_46 = wx.BoxSizer(wx.HORIZONTAL)

        label_11 = wx.StaticText(self.panel_51, wx.ID_ANY, "Displayed PC in X:")
        label_11.SetMinSize((93, 18))
        label_11.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_46.Add(label_11, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 25)

        self.combo_box_2 = wx.ComboBox(self.panel_44, wx.ID_ANY, choices=["1", "2", "3", "4"], style=wx.CB_DROPDOWN)
        sizer_42.Add(self.combo_box_2, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 5)

        self.panel_48 = wx.Panel(self.panel_44, wx.ID_ANY)
        sizer_41.Add(self.panel_48, 1, wx.EXPAND, 0)

        sizer_43 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_38.Add(sizer_43, 1, wx.EXPAND, 0)

        sizer_44 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_43.Add(sizer_44, 3, 0, 0)

        self.panel_52 = wx.Panel(self.panel_44, wx.ID_ANY)
        sizer_44.Add(self.panel_52, 3, wx.EXPAND, 0)

        sizer_47 = wx.BoxSizer(wx.HORIZONTAL)

        label_12 = wx.StaticText(self.panel_52, wx.ID_ANY, "Displayed PC in Y:")
        label_12.SetMinSize((93, 18))
        label_12.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_47.Add(label_12, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 25)

        self.combo_box_3 = wx.ComboBox(self.panel_44, wx.ID_ANY, choices=["1", "2", "3", "4"], style=wx.CB_DROPDOWN)
        sizer_44.Add(self.combo_box_3, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 5)

        self.panel_54 = wx.Panel(self.panel_44, wx.ID_ANY)
        sizer_43.Add(self.panel_54, 1, wx.EXPAND, 0)

        sizer_48 = wx.BoxSizer(wx.VERTICAL)

        self.button_3 = wx.Button(self.panel_54, wx.ID_ANY, "Run")
        self.button_3.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_48.Add(self.button_3, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.EXPAND | wx.SHAPED, 3)

        self.panel_53 = wx.Panel(self.panel_41, wx.ID_ANY, style=wx.BORDER_THEME)
        sizer_36.Add(self.panel_53, 1, wx.EXPAND, 0)

        sizer_49 = wx.BoxSizer(wx.HORIZONTAL)

        self.button_4 = wx.Button(self.panel_53, wx.ID_ANY, "Download\nplot")
        self.button_4.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_49.Add(self.button_4, 1, wx.ALL | wx.EXPAND, 8)

        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1_pane_2.SetBackgroundColour(wx.Colour(188, 188, 188))
        self.notebook_1.AddPage(self.notebook_1_pane_2, "New entry to database")

        sizer_3 = wx.BoxSizer(wx.VERTICAL)

        self.panel_7 = wx.Panel(self.notebook_1_pane_2, wx.ID_ANY, style=wx.CLIP_CHILDREN | wx.FULL_REPAINT_ON_RESIZE)
        self.panel_7.SetMinSize((1000, 35))
        self.panel_7.SetBackgroundColour(wx.Colour(252, 255, 116))
        sizer_3.Add(self.panel_7, 0, wx.ALL | wx.EXPAND, 5)

        sizer_9 = wx.BoxSizer(wx.VERTICAL)

        label_2 = wx.StaticText(self.panel_7, wx.ID_ANY, "Welcome to Aquasearch", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_2.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_9.Add(label_2, 0, wx.BOTTOM | wx.EXPAND, 5)

        self.panel_8 = wx.Panel(self.notebook_1_pane_2, wx.ID_ANY, style=wx.CLIP_CHILDREN | wx.FULL_REPAINT_ON_RESIZE)
        self.panel_8.SetMinSize((1000, 35))
        self.panel_8.SetBackgroundColour(wx.Colour(0, 127, 255))
        sizer_3.Add(self.panel_8, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 5)

        sizer_10 = wx.BoxSizer(wx.VERTICAL)

        self.panel_15 = wx.Panel(self.panel_8, wx.ID_ANY)
        sizer_10.Add(self.panel_15, 1, wx.ALL | wx.EXPAND, 5)

        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_55 = wx.Panel(self.panel_15, wx.ID_ANY)
        self.panel_55.SetMinSize((140, 6))
        sizer_11.Add(self.panel_55, 0, wx.EXPAND, 0)

        sizer_50 = wx.BoxSizer(wx.VERTICAL)

        label_13 = wx.StaticText(self.panel_55, wx.ID_ANY, "Select database")
        label_13.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_50.Add(label_13, 1, wx.ALIGN_RIGHT | wx.RIGHT, 15)

        self.panel_56 = wx.Panel(self.panel_15, wx.ID_ANY)
        self.panel_56.SetMinSize((300, 6))
        sizer_11.Add(self.panel_56, 1, wx.EXPAND, 0)

        sizer_51 = wx.BoxSizer(wx.VERTICAL)

        self.combo_box_4 = wx.ComboBox(self.panel_56, wx.ID_ANY, choices=["Aquasearch_study", "New database"], style=wx.CB_DROPDOWN)
        sizer_51.Add(self.combo_box_4, 1, wx.EXPAND, 0)

        self.panel_57 = wx.Panel(self.notebook_1_pane_2, wx.ID_ANY)
        sizer_3.Add(self.panel_57, 1, wx.EXPAND, 0)

        sizer_52 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_58 = wx.Panel(self.panel_57, wx.ID_ANY)
        sizer_52.Add(self.panel_58, 1, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 5)

        sizer_53 = wx.BoxSizer(wx.HORIZONTAL)

        self.notebook_2 = wx.Notebook(self.panel_58, wx.ID_ANY)
        sizer_53.Add(self.notebook_2, 1, wx.EXPAND, 0)

        self.notebook_2_pane_1 = wx.Panel(self.notebook_2, wx.ID_ANY)
        self.notebook_2.AddPage(self.notebook_2_pane_1, "1 protein per label")

        sizer_54 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_62 = wx.Panel(self.notebook_2_pane_1, wx.ID_ANY, style=wx.BORDER_THEME)
        self.panel_62.SetBackgroundColour(wx.Colour(217, 255, 225))
        sizer_54.Add(self.panel_62, 1, wx.EXPAND, 0)

        sizer_55 = wx.BoxSizer(wx.VERTICAL)

        self.panel_60 = wx.Panel(self.panel_62, wx.ID_ANY)
        self.panel_60.SetMinSize((-1, 35))
        sizer_55.Add(self.panel_60, 0, wx.EXPAND, 0)

        sizer_58 = wx.BoxSizer(wx.VERTICAL)

        label_14 = wx.StaticText(self.panel_60, wx.ID_ANY, "Mixure of proteins")
        label_14.SetFont(wx.Font(13, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_58.Add(label_14, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.TOP, 5)

        self.panel_61 = wx.Panel(self.panel_62, wx.ID_ANY)
        self.panel_61.SetMinSize((-1, 50))
        sizer_55.Add(self.panel_61, 0, wx.EXPAND, 0)

        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_59 = wx.Panel(self.panel_61, wx.ID_ANY)
        self.panel_59.SetMinSize((180, 30))
        sizer_12.Add(self.panel_59, 0, wx.EXPAND, 0)

        sizer_56 = wx.BoxSizer(wx.VERTICAL)

        label_16 = wx.StaticText(self.panel_59, wx.ID_ANY, "Mixure file from MALDI-TOF (txt)")
        label_16.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_56.Add(label_16, 1, wx.ALIGN_RIGHT | wx.ALL, 8)

        self.panel_71 = wx.Panel(self.panel_61, wx.ID_ANY)
        sizer_12.Add(self.panel_71, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 5)

        sizer_60 = wx.BoxSizer(wx.VERTICAL)

        self.button_5 = filebrowse.FileBrowseButton(self.panel_71, wx.ID_ANY, changeCallback = self.fbbCallback, dialogTitle= 'Import')
        sizer_60.Add(self.button_5, 1, wx.ALL | wx.EXPAND, 5)

        self.panel_63 = wx.Panel(self.panel_62, wx.ID_ANY)
        self.panel_63.SetMinSize((-1, 50))
        sizer_55.Add(self.panel_63, 0, wx.EXPAND, 0)

        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_72 = wx.Panel(self.panel_63, wx.ID_ANY)
        self.panel_72.SetMinSize((180, 30))
        sizer_13.Add(self.panel_72, 0, wx.EXPAND, 0)

        sizer_61 = wx.BoxSizer(wx.VERTICAL)

        label_17 = wx.StaticText(self.panel_72, wx.ID_ANY, "Peptide data form Proteome Discoverer (xlsx)")
        label_17.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_61.Add(label_17, 1, wx.ALIGN_RIGHT | wx.ALL, 8)

        self.panel_73 = wx.Panel(self.panel_63, wx.ID_ANY)
        sizer_13.Add(self.panel_73, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 5)

        sizer_62 = wx.BoxSizer(wx.VERTICAL)

        self.button_6 = filebrowse.FileBrowseButton(self.panel_73, wx.ID_ANY, changeCallback = self.fbbCallback, dialogTitle= 'Import')
        sizer_62.Add(self.button_6, 1, wx.ALL | wx.EXPAND, 5)

        self.panel_64 = wx.Panel(self.panel_62, wx.ID_ANY)
        self.panel_64.SetMinSize((-1, 50))
        sizer_55.Add(self.panel_64, 0, wx.EXPAND, 0)

        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_74 = wx.Panel(self.panel_64, wx.ID_ANY)
        self.panel_74.SetMinSize((180, 30))
        sizer_17.Add(self.panel_74, 0, wx.EXPAND, 0)

        sizer_63 = wx.BoxSizer(wx.VERTICAL)

        label_18 = wx.StaticText(self.panel_74, wx.ID_ANY, "Protein data form Proteome Discoverer (xlsx)")
        label_18.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_63.Add(label_18, 1, wx.ALIGN_RIGHT | wx.ALL, 8)

        self.panel_75 = wx.Panel(self.panel_64, wx.ID_ANY)
        sizer_17.Add(self.panel_75, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 5)

        sizer_64 = wx.BoxSizer(wx.VERTICAL)

        self.button_7 = filebrowse.FileBrowseButton(self.panel_75, wx.ID_ANY, changeCallback = self.fbbCallback, dialogTitle= 'Import')
        sizer_64.Add(self.button_7, 1, wx.ALL | wx.EXPAND, 5)

        self.panel_65 = wx.Panel(self.panel_62, wx.ID_ANY)
        self.panel_65.SetMinSize((-1, 60))
        sizer_55.Add(self.panel_65, 0, wx.EXPAND, 0)

        sizer_65 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_77 = wx.Panel(self.panel_65, wx.ID_ANY)
        self.panel_77.SetMinSize((100, 60))
        sizer_65.Add(self.panel_77, 0, wx.EXPAND, 0)

        sizer_66 = wx.BoxSizer(wx.VERTICAL)

        label_19 = wx.StaticText(self.panel_77, wx.ID_ANY, "ppm:  ")
        label_19.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_66.Add(label_19, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 18)

        self.panel_78 = wx.Panel(self.panel_65, wx.ID_ANY)
        sizer_65.Add(self.panel_78, 1, wx.EXPAND, 0)

        sizer_67 = wx.BoxSizer(wx.VERTICAL)

        self.spin_ctrl_1 = wx.SpinCtrl(self.panel_78, wx.ID_ANY, "100", min=0, max=150, style=wx.ALIGN_RIGHT | wx.SP_ARROW_KEYS)
        self.spin_ctrl_1.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_67.Add(self.spin_ctrl_1, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 17)

        self.panel_79 = wx.Panel(self.panel_65, wx.ID_ANY)
        self.panel_79.SetMinSize((100, 60))
        sizer_65.Add(self.panel_79, 0, wx.EXPAND, 0)

        sizer_68 = wx.BoxSizer(wx.VERTICAL)

        label_20 = wx.StaticText(self.panel_79, wx.ID_ANY, "Unique peptides  ")
        label_20.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_68.Add(label_20, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 18)

        self.panel_80 = wx.Panel(self.panel_65, wx.ID_ANY)
        sizer_65.Add(self.panel_80, 1, wx.EXPAND, 0)

        sizer_69 = wx.BoxSizer(wx.VERTICAL)

        self.combo_box_5 = wx.ComboBox(self.panel_80, wx.ID_ANY, choices=["Selection ", "All posibilities"], style=wx.CB_DROPDOWN)
        self.combo_box_5.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_69.Add(self.combo_box_5, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 17)

        self.panel_66 = wx.Panel(self.panel_62, wx.ID_ANY)
        self.panel_66.SetMinSize((-1, 60))
        sizer_55.Add(self.panel_66, 0, wx.EXPAND, 0)

        sizer_70 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_81 = wx.Panel(self.panel_66, wx.ID_ANY)
        self.panel_81.SetMinSize((100, 60))
        sizer_70.Add(self.panel_81, 0, wx.EXPAND, 0)

        sizer_71 = wx.BoxSizer(wx.VERTICAL)

        label_21 = wx.StaticText(self.panel_81, wx.ID_ANY, "Uniprot code:  ")
        label_21.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_71.Add(label_21, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 18)

        self.panel_82 = wx.Panel(self.panel_66, wx.ID_ANY)
        sizer_70.Add(self.panel_82, 1, wx.EXPAND, 0)

        sizer_72 = wx.BoxSizer(wx.VERTICAL)

        self.text_ctrl_1 = wx.TextCtrl(self.panel_82, wx.ID_ANY, "Ej. P19121")
        self.text_ctrl_1.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_72.Add(self.text_ctrl_1, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 17)

        self.panel_83 = wx.Panel(self.panel_66, wx.ID_ANY)
        self.panel_83.SetMinSize((100, 60))
        sizer_70.Add(self.panel_83, 0, wx.EXPAND, 0)

        sizer_73 = wx.BoxSizer(wx.VERTICAL)

        label_22 = wx.StaticText(self.panel_83, wx.ID_ANY, "Protein rank  ")
        label_22.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_73.Add(label_22, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 18)

        self.panel_84 = wx.Panel(self.panel_66, wx.ID_ANY)
        sizer_70.Add(self.panel_84, 1, wx.EXPAND, 0)

        sizer_74 = wx.BoxSizer(wx.VERTICAL)

        self.spin_ctrl_2 = wx.SpinCtrl(self.panel_84, wx.ID_ANY, "200", min=0, max=500, style=wx.ALIGN_RIGHT | wx.SP_ARROW_KEYS)
        self.spin_ctrl_2.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_74.Add(self.spin_ctrl_2, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 17)

        self.panel_67 = wx.Panel(self.panel_62, wx.ID_ANY)
        self.panel_67.SetMinSize((-1, 60))
        sizer_55.Add(self.panel_67, 0, wx.EXPAND, 0)

        sizer_75 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_85 = wx.Panel(self.panel_67, wx.ID_ANY)
        self.panel_85.SetMinSize((100, 60))
        sizer_75.Add(self.panel_85, 0, wx.EXPAND, 0)

        sizer_77 = wx.BoxSizer(wx.VERTICAL)

        label_23 = wx.StaticText(self.panel_85, wx.ID_ANY, "Sample name:  ")
        label_23.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_77.Add(label_23, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 18)

        self.panel_87 = wx.Panel(self.panel_67, wx.ID_ANY)
        sizer_75.Add(self.panel_87, 1, wx.EXPAND, 0)

        sizer_78 = wx.BoxSizer(wx.VERTICAL)

        self.text_ctrl_2 = wx.TextCtrl(self.panel_87, wx.ID_ANY, "Use specific names")
        self.text_ctrl_2.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_78.Add(self.text_ctrl_2, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 17)

        self.panel_86 = wx.Panel(self.panel_62, wx.ID_ANY)
        sizer_55.Add(self.panel_86, 1, wx.EXPAND, 0)

        self.panel_76 = wx.Panel(self.panel_62, wx.ID_ANY)
        self.panel_76.SetMinSize((-1, 35))
        sizer_55.Add(self.panel_76, 0, wx.EXPAND, 0)

        sizer_76 = wx.BoxSizer(wx.VERTICAL)

        self.button_9 = wx.Button(self.panel_76, wx.ID_ANY, "Run")
        sizer_76.Add(self.button_9, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.RIGHT, 4)

        self.panel_68 = wx.Panel(self.notebook_2_pane_1, wx.ID_ANY, style=wx.BORDER_THEME)
        self.panel_68.SetBackgroundColour(wx.Colour(255, 233, 201))
        sizer_54.Add(self.panel_68, 1, wx.EXPAND, 0)

        sizer_57 = wx.BoxSizer(wx.VERTICAL)

        self.panel_70 = wx.Panel(self.panel_68, wx.ID_ANY)
        self.panel_70.SetMinSize((-1, 35))
        sizer_57.Add(self.panel_70, 0, wx.EXPAND, 0)

        sizer_59 = wx.BoxSizer(wx.VERTICAL)

        label_15 = wx.StaticText(self.panel_70, wx.ID_ANY, "Standard protein")
        label_15.SetFont(wx.Font(13, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_59.Add(label_15, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.TOP, 5)

        self.panel_117 = wx.Panel(self.panel_68, wx.ID_ANY)
        self.panel_117.SetMinSize((-1, 50))
        sizer_57.Add(self.panel_117, 0, wx.EXPAND, 0)

        sizer_105 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_118 = wx.Panel(self.panel_117, wx.ID_ANY)
        self.panel_118.SetMinSize((180, 30))
        sizer_105.Add(self.panel_118, 0, wx.EXPAND, 0)

        sizer_106 = wx.BoxSizer(wx.VERTICAL)

        label_33 = wx.StaticText(self.panel_118, wx.ID_ANY, "Mixure file from MALDI-TOF (txt)")
        label_33.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_106.Add(label_33, 1, wx.ALIGN_RIGHT | wx.ALL, 8)

        self.panel_124 = wx.Panel(self.panel_117, wx.ID_ANY)
        sizer_105.Add(self.panel_124, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 5)

        sizer_112 = wx.BoxSizer(wx.VERTICAL)

        self.button_12 = filebrowse.FileBrowseButton(self.panel_124, wx.ID_ANY, changeCallback = self.fbbCallback, dialogTitle= 'Import')
        sizer_112.Add(self.button_12, 1, wx.ALL | wx.EXPAND, 5)

        self.panel_125 = wx.Panel(self.panel_68, wx.ID_ANY)
        self.panel_125.SetMinSize((-1, 50))
        sizer_57.Add(self.panel_125, 0, wx.EXPAND, 0)

        sizer_113 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_126 = wx.Panel(self.panel_125, wx.ID_ANY)
        self.panel_126.SetMinSize((180, 30))
        sizer_113.Add(self.panel_126, 0, wx.EXPAND, 0)

        sizer_114 = wx.BoxSizer(wx.VERTICAL)

        label_36 = wx.StaticText(self.panel_126, wx.ID_ANY, "Unique/non-unique peptide information (xlsx)")
        label_36.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_114.Add(label_36, 1, wx.ALIGN_RIGHT | wx.ALL, 8)

        self.panel_127 = wx.Panel(self.panel_125, wx.ID_ANY)
        sizer_113.Add(self.panel_127, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 5)

        sizer_115 = wx.BoxSizer(wx.VERTICAL)

        self.button_14 = filebrowse.FileBrowseButton(self.panel_127, wx.ID_ANY, changeCallback = self.fbbCallback, dialogTitle= 'Import')
        sizer_115.Add(self.button_14, 1, wx.ALL | wx.EXPAND, 5)

        self.panel_9 = wx.Panel(self.panel_68, wx.ID_ANY)
        self.panel_9.SetMinSize((-1, 30))
        sizer_57.Add(self.panel_9, 0, wx.EXPAND, 0)

        self.panel_133 = wx.Panel(self.panel_68, wx.ID_ANY)
        self.panel_133.SetMinSize((-1, 60))
        sizer_57.Add(self.panel_133, 0, wx.EXPAND, 0)

        sizer_121 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_134 = wx.Panel(self.panel_133, wx.ID_ANY)
        self.panel_134.SetMinSize((100, 60))
        sizer_121.Add(self.panel_134, 0, wx.EXPAND, 0)

        sizer_122 = wx.BoxSizer(wx.VERTICAL)

        label_39 = wx.StaticText(self.panel_134, wx.ID_ANY, "ppm:  ")
        label_39.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_122.Add(label_39, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 18)

        self.panel_135 = wx.Panel(self.panel_133, wx.ID_ANY)
        sizer_121.Add(self.panel_135, 1, wx.EXPAND, 0)

        sizer_123 = wx.BoxSizer(wx.VERTICAL)

        self.spin_ctrl_6 = wx.SpinCtrl(self.panel_135, wx.ID_ANY, "100", min=0, max=150, style=wx.ALIGN_RIGHT | wx.SP_ARROW_KEYS)
        self.spin_ctrl_6.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_123.Add(self.spin_ctrl_6, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 17)

        self.panel_136 = wx.Panel(self.panel_133, wx.ID_ANY)
        self.panel_136.SetMinSize((100, 60))
        sizer_121.Add(self.panel_136, 0, wx.EXPAND, 0)

        sizer_124 = wx.BoxSizer(wx.VERTICAL)

        label_40 = wx.StaticText(self.panel_136, wx.ID_ANY, "Uniprot code:  ")
        label_40.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_124.Add(label_40, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 18)

        self.panel_137 = wx.Panel(self.panel_133, wx.ID_ANY)
        sizer_121.Add(self.panel_137, 1, wx.EXPAND, 0)

        sizer_125 = wx.BoxSizer(wx.VERTICAL)

        self.text_ctrl_8 = wx.TextCtrl(self.panel_137, wx.ID_ANY, "Ej. P19121")
        self.text_ctrl_8.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_125.Add(self.text_ctrl_8, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 17)

        self.panel_128 = wx.Panel(self.panel_68, wx.ID_ANY)
        self.panel_128.SetMinSize((-1, 60))
        sizer_57.Add(self.panel_128, 0, wx.EXPAND, 0)

        sizer_116 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_129 = wx.Panel(self.panel_128, wx.ID_ANY)
        self.panel_129.SetMinSize((100, 60))
        sizer_116.Add(self.panel_129, 0, wx.EXPAND, 0)

        sizer_117 = wx.BoxSizer(wx.VERTICAL)

        label_37 = wx.StaticText(self.panel_129, wx.ID_ANY, "Sample name:  ")
        label_37.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_117.Add(label_37, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 18)

        self.panel_130 = wx.Panel(self.panel_128, wx.ID_ANY)
        sizer_116.Add(self.panel_130, 1, wx.EXPAND, 0)

        sizer_118 = wx.BoxSizer(wx.VERTICAL)

        self.text_ctrl_7 = wx.TextCtrl(self.panel_130, wx.ID_ANY, "Use specific names")
        self.text_ctrl_7.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_118.Add(self.text_ctrl_7, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 17)

        self.panel_156 = wx.Panel(self.panel_68, wx.ID_ANY)
        sizer_57.Add(self.panel_156, 1, wx.EXPAND, 0)

        self.panel_157 = wx.Panel(self.panel_68, wx.ID_ANY)
        self.panel_157.SetMinSize((-1, 35))
        sizer_57.Add(self.panel_157, 0, wx.EXPAND, 0)

        sizer_119 = wx.BoxSizer(wx.VERTICAL)

        self.button_17 = wx.Button(self.panel_157, wx.ID_ANY, "Run")
        sizer_119.Add(self.button_17, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.RIGHT, 4)

        self.notebook_2_pane_2 = wx.Panel(self.notebook_2, wx.ID_ANY)
        self.notebook_2.AddPage(self.notebook_2_pane_2, "2 proteins per label")

        sizer_79 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_69 = wx.Panel(self.notebook_2_pane_2, wx.ID_ANY, style=wx.BORDER_THEME)
        self.panel_69.SetBackgroundColour(wx.Colour(217, 255, 225))
        sizer_79.Add(self.panel_69, 1, wx.EXPAND, 0)

        sizer_80 = wx.BoxSizer(wx.VERTICAL)

        self.panel_90 = wx.Panel(self.panel_69, wx.ID_ANY)
        self.panel_90.SetMinSize((-1, 35))
        sizer_80.Add(self.panel_90, 0, wx.EXPAND, 0)

        sizer_81 = wx.BoxSizer(wx.VERTICAL)

        label_24 = wx.StaticText(self.panel_90, wx.ID_ANY, "Mixure of proteins")
        label_24.SetFont(wx.Font(13, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_81.Add(label_24, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.TOP, 5)

        self.panel_91 = wx.Panel(self.panel_69, wx.ID_ANY)
        self.panel_91.SetMinSize((-1, 50))
        sizer_80.Add(self.panel_91, 0, wx.EXPAND, 0)

        sizer_82 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_92 = wx.Panel(self.panel_91, wx.ID_ANY)
        self.panel_92.SetMinSize((180, 30))
        sizer_82.Add(self.panel_92, 0, wx.EXPAND, 0)

        sizer_83 = wx.BoxSizer(wx.VERTICAL)

        label_25 = wx.StaticText(self.panel_92, wx.ID_ANY, "Mixure file from MALDI-TOF (txt)")
        label_25.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_83.Add(label_25, 1, wx.ALIGN_RIGHT | wx.ALL, 8)

        self.panel_93 = wx.Panel(self.panel_91, wx.ID_ANY)
        sizer_82.Add(self.panel_93, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 5)

        sizer_84 = wx.BoxSizer(wx.VERTICAL)

        self.button_8 = filebrowse.FileBrowseButton(self.panel_93, wx.ID_ANY, changeCallback = self.fbbCallback, dialogTitle= 'Import')
        sizer_84.Add(self.button_8, 1, wx.ALL | wx.EXPAND, 5)

        self.panel_94 = wx.Panel(self.panel_69, wx.ID_ANY)
        self.panel_94.SetMinSize((-1, 50))
        sizer_80.Add(self.panel_94, 0, wx.EXPAND, 0)

        sizer_85 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_95 = wx.Panel(self.panel_94, wx.ID_ANY)
        self.panel_95.SetMinSize((180, 30))
        sizer_85.Add(self.panel_95, 0, wx.EXPAND, 0)

        sizer_86 = wx.BoxSizer(wx.VERTICAL)

        label_26 = wx.StaticText(self.panel_95, wx.ID_ANY, "Peptide data form Proteome Discoverer (xlsx)")
        label_26.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_86.Add(label_26, 1, wx.ALIGN_RIGHT | wx.ALL, 8)

        self.panel_96 = wx.Panel(self.panel_94, wx.ID_ANY)
        sizer_85.Add(self.panel_96, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 5)

        sizer_87 = wx.BoxSizer(wx.VERTICAL)

        self.button_10 = filebrowse.FileBrowseButton(self.panel_96, wx.ID_ANY, changeCallback = self.fbbCallback, dialogTitle= 'Import')
        sizer_87.Add(self.button_10, 1, wx.ALL | wx.EXPAND, 5)

        self.panel_97 = wx.Panel(self.panel_69, wx.ID_ANY)
        self.panel_97.SetMinSize((-1, 50))
        sizer_80.Add(self.panel_97, 0, wx.EXPAND, 0)

        sizer_88 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_98 = wx.Panel(self.panel_97, wx.ID_ANY)
        self.panel_98.SetMinSize((180, 30))
        sizer_88.Add(self.panel_98, 0, wx.EXPAND, 0)

        sizer_89 = wx.BoxSizer(wx.VERTICAL)

        label_27 = wx.StaticText(self.panel_98, wx.ID_ANY, "Protein data form Proteome Discoverer (xlsx)")
        label_27.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_89.Add(label_27, 1, wx.ALIGN_RIGHT | wx.ALL, 8)

        self.panel_99 = wx.Panel(self.panel_97, wx.ID_ANY)
        sizer_88.Add(self.panel_99, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 5)

        sizer_90 = wx.BoxSizer(wx.VERTICAL)

        self.button_11 = filebrowse.FileBrowseButton(self.panel_99, wx.ID_ANY, changeCallback = self.fbbCallback, dialogTitle= 'Import')
        sizer_90.Add(self.button_11, 1, wx.ALL | wx.EXPAND, 5)

        self.panel_100 = wx.Panel(self.panel_69, wx.ID_ANY)
        self.panel_100.SetMinSize((-1, 50))
        sizer_80.Add(self.panel_100, 0, wx.EXPAND, 0)

        sizer_91 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_101 = wx.Panel(self.panel_100, wx.ID_ANY)
        self.panel_101.SetMinSize((100, 60))
        sizer_91.Add(self.panel_101, 0, wx.EXPAND, 0)

        sizer_92 = wx.BoxSizer(wx.VERTICAL)

        label_28 = wx.StaticText(self.panel_101, wx.ID_ANY, "ppm:  ")
        label_28.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_92.Add(label_28, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 15)

        self.panel_102 = wx.Panel(self.panel_100, wx.ID_ANY)
        sizer_91.Add(self.panel_102, 1, wx.EXPAND, 0)

        sizer_93 = wx.BoxSizer(wx.VERTICAL)

        self.spin_ctrl_3 = wx.SpinCtrl(self.panel_102, wx.ID_ANY, "100", min=0, max=150, style=wx.ALIGN_RIGHT | wx.SP_ARROW_KEYS)
        self.spin_ctrl_3.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_93.Add(self.spin_ctrl_3, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 14)

        self.panel_103 = wx.Panel(self.panel_100, wx.ID_ANY)
        self.panel_103.SetMinSize((100, 60))
        sizer_91.Add(self.panel_103, 0, wx.EXPAND, 0)

        sizer_94 = wx.BoxSizer(wx.VERTICAL)

        label_29 = wx.StaticText(self.panel_103, wx.ID_ANY, "Unique peptides  ")
        label_29.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_94.Add(label_29, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 15)

        self.panel_104 = wx.Panel(self.panel_100, wx.ID_ANY)
        sizer_91.Add(self.panel_104, 1, wx.EXPAND, 0)

        sizer_95 = wx.BoxSizer(wx.VERTICAL)

        self.combo_box_6 = wx.ComboBox(self.panel_104, wx.ID_ANY, choices=["Selection ", "All posibilities"], style=wx.CB_DROPDOWN)
        self.combo_box_6.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_95.Add(self.combo_box_6, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 14)

        self.panel_105 = wx.Panel(self.panel_69, wx.ID_ANY)
        self.panel_105.SetMinSize((-1, 50))
        sizer_80.Add(self.panel_105, 0, wx.EXPAND, 0)

        sizer_96 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_106 = wx.Panel(self.panel_105, wx.ID_ANY)
        self.panel_106.SetMinSize((100, 60))
        sizer_96.Add(self.panel_106, 0, wx.EXPAND, 0)

        sizer_97 = wx.BoxSizer(wx.VERTICAL)

        label_30 = wx.StaticText(self.panel_106, wx.ID_ANY, "Uniprot code 1:  ")
        label_30.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_97.Add(label_30, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 15)

        self.panel_107 = wx.Panel(self.panel_105, wx.ID_ANY)
        sizer_96.Add(self.panel_107, 1, wx.EXPAND, 0)

        sizer_98 = wx.BoxSizer(wx.VERTICAL)

        self.text_ctrl_3 = wx.TextCtrl(self.panel_107, wx.ID_ANY, "Ej. P02770")
        self.text_ctrl_3.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_98.Add(self.text_ctrl_3, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 14)

        self.panel_108 = wx.Panel(self.panel_105, wx.ID_ANY)
        self.panel_108.SetMinSize((100, 60))
        sizer_96.Add(self.panel_108, 0, wx.EXPAND, 0)

        sizer_99 = wx.BoxSizer(wx.VERTICAL)

        label_31 = wx.StaticText(self.panel_108, wx.ID_ANY, "Uniprot code 2:  ")
        label_31.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_99.Add(label_31, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 15)

        self.panel_109 = wx.Panel(self.panel_105, wx.ID_ANY)
        sizer_96.Add(self.panel_109, 1, wx.EXPAND, 0)

        sizer_100 = wx.BoxSizer(wx.VERTICAL)

        self.text_ctrl_6 = wx.TextCtrl(self.panel_109, wx.ID_ANY, "Ej. P07724")
        self.text_ctrl_6.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_100.Add(self.text_ctrl_6, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 14)

        self.panel_110 = wx.Panel(self.panel_69, wx.ID_ANY)
        self.panel_110.SetMinSize((-1, 50))
        sizer_80.Add(self.panel_110, 0, wx.EXPAND, 0)

        sizer_101 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_111 = wx.Panel(self.panel_110, wx.ID_ANY)
        self.panel_111.SetMinSize((100, 60))
        sizer_101.Add(self.panel_111, 0, wx.EXPAND, 0)

        sizer_102 = wx.BoxSizer(wx.VERTICAL)

        label_32 = wx.StaticText(self.panel_111, wx.ID_ANY, "Grouping name:  ")
        label_32.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_102.Add(label_32, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 15)

        self.panel_112 = wx.Panel(self.panel_110, wx.ID_ANY)
        sizer_101.Add(self.panel_112, 1, wx.EXPAND, 0)

        sizer_103 = wx.BoxSizer(wx.VERTICAL)

        self.text_ctrl_4 = wx.TextCtrl(self.panel_112, wx.ID_ANY, "Ej. Murid albumin")
        self.text_ctrl_4.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_103.Add(self.text_ctrl_4, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 14)

        self.panel_113 = wx.Panel(self.panel_110, wx.ID_ANY)
        self.panel_113.SetMinSize((100, 60))
        sizer_101.Add(self.panel_113, 0, wx.EXPAND, 0)

        sizer_110 = wx.BoxSizer(wx.VERTICAL)

        label_35 = wx.StaticText(self.panel_113, wx.ID_ANY, "Protein rank  ")
        label_35.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_110.Add(label_35, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 15)

        self.panel_114 = wx.Panel(self.panel_110, wx.ID_ANY)
        sizer_101.Add(self.panel_114, 1, wx.EXPAND, 0)

        sizer_111 = wx.BoxSizer(wx.VERTICAL)

        self.spin_ctrl_5 = wx.SpinCtrl(self.panel_114, wx.ID_ANY, "200", min=0, max=500, style=wx.ALIGN_RIGHT | wx.SP_ARROW_KEYS)
        self.spin_ctrl_5.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_111.Add(self.spin_ctrl_5, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 14)

        self.panel_115 = wx.Panel(self.panel_69, wx.ID_ANY)
        self.panel_115.SetMinSize((-1, 50))
        sizer_80.Add(self.panel_115, 0, wx.EXPAND, 0)

        sizer_104 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_120 = wx.Panel(self.panel_115, wx.ID_ANY)
        self.panel_120.SetMinSize((100, 60))
        sizer_104.Add(self.panel_120, 0, wx.EXPAND, 0)

        sizer_108 = wx.BoxSizer(wx.VERTICAL)

        label_34 = wx.StaticText(self.panel_120, wx.ID_ANY, "Sample name:  ")
        label_34.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_108.Add(label_34, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 15)

        self.panel_121 = wx.Panel(self.panel_115, wx.ID_ANY)
        sizer_104.Add(self.panel_121, 1, wx.EXPAND, 0)

        sizer_109 = wx.BoxSizer(wx.VERTICAL)

        self.text_ctrl_5 = wx.TextCtrl(self.panel_121, wx.ID_ANY, "Use specific names")
        self.text_ctrl_5.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_109.Add(self.text_ctrl_5, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 14)

        self.panel_116 = wx.Panel(self.panel_69, wx.ID_ANY)
        sizer_80.Add(self.panel_116, 1, wx.EXPAND, 0)

        self.panel_119 = wx.Panel(self.panel_69, wx.ID_ANY)
        self.panel_119.SetMinSize((-1, 35))
        sizer_80.Add(self.panel_119, 0, wx.EXPAND, 0)

        sizer_107 = wx.BoxSizer(wx.VERTICAL)

        self.button_13 = wx.Button(self.panel_119, wx.ID_ANY, "Run")
        sizer_107.Add(self.button_13, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.RIGHT, 4)

        self.panel_138 = wx.Panel(self.notebook_2_pane_2, wx.ID_ANY, style=wx.BORDER_THEME)
        self.panel_138.SetBackgroundColour(wx.Colour(255, 233, 201))
        sizer_79.Add(self.panel_138, 1, wx.EXPAND, 0)

        sizer_120 = wx.BoxSizer(wx.VERTICAL)

        self.panel_139 = wx.Panel(self.panel_138, wx.ID_ANY)
        self.panel_139.SetMinSize((-1, 35))
        sizer_120.Add(self.panel_139, 0, wx.EXPAND, 0)

        sizer_126 = wx.BoxSizer(wx.VERTICAL)

        label_38 = wx.StaticText(self.panel_139, wx.ID_ANY, "Standard protein")
        label_38.SetFont(wx.Font(13, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        sizer_126.Add(label_38, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.TOP, 5)

        self.panel_140 = wx.Panel(self.panel_138, wx.ID_ANY)
        self.panel_140.SetMinSize((-1, 50))
        sizer_120.Add(self.panel_140, 0, wx.EXPAND, 0)

        sizer_127 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_141 = wx.Panel(self.panel_140, wx.ID_ANY)
        self.panel_141.SetMinSize((180, 30))
        sizer_127.Add(self.panel_141, 0, wx.EXPAND, 0)

        sizer_128 = wx.BoxSizer(wx.VERTICAL)

        label_41 = wx.StaticText(self.panel_141, wx.ID_ANY, "Mixure file from MALDI-TOF (txt)")
        label_41.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_128.Add(label_41, 1, wx.ALIGN_RIGHT | wx.ALL, 8)

        self.panel_142 = wx.Panel(self.panel_140, wx.ID_ANY)
        sizer_127.Add(self.panel_142, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 5)

        sizer_129 = wx.BoxSizer(wx.VERTICAL)

        self.button_15 = filebrowse.FileBrowseButton(self.panel_142, wx.ID_ANY, changeCallback = self.fbbCallback, dialogTitle= 'Import')
        sizer_129.Add(self.button_15, 1, wx.ALL | wx.EXPAND, 5)

        self.panel_143 = wx.Panel(self.panel_138, wx.ID_ANY)
        self.panel_143.SetMinSize((-1, 50))
        sizer_120.Add(self.panel_143, 0, wx.EXPAND, 0)

        sizer_130 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_144 = wx.Panel(self.panel_143, wx.ID_ANY)
        self.panel_144.SetMinSize((180, 30))
        sizer_130.Add(self.panel_144, 0, wx.EXPAND, 0)

        sizer_131 = wx.BoxSizer(wx.VERTICAL)

        label_42 = wx.StaticText(self.panel_144, wx.ID_ANY, "Unique/non-unique peptide information (xlsx)")
        label_42.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_131.Add(label_42, 1, wx.ALIGN_RIGHT | wx.ALL, 8)

        self.panel_145 = wx.Panel(self.panel_143, wx.ID_ANY)
        sizer_130.Add(self.panel_145, 1, wx.BOTTOM | wx.EXPAND | wx.TOP, 5)

        sizer_132 = wx.BoxSizer(wx.VERTICAL)

        self.button_16 = filebrowse.FileBrowseButton(self.panel_145, wx.ID_ANY, changeCallback = self.fbbCallback, dialogTitle= 'Import')
        sizer_132.Add(self.button_16, 1, wx.ALL | wx.EXPAND, 5)

        self.panel_10 = wx.Panel(self.panel_138, wx.ID_ANY)
        self.panel_10.SetMinSize((-1, 30))
        sizer_120.Add(self.panel_10, 0, wx.EXPAND, 0)

        self.panel_146 = wx.Panel(self.panel_138, wx.ID_ANY)
        self.panel_146.SetMinSize((-1, 60))
        sizer_120.Add(self.panel_146, 0, wx.EXPAND, 0)

        sizer_133 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_147 = wx.Panel(self.panel_146, wx.ID_ANY)
        self.panel_147.SetMinSize((100, 60))
        sizer_133.Add(self.panel_147, 0, wx.EXPAND, 0)

        sizer_134 = wx.BoxSizer(wx.VERTICAL)

        label_43 = wx.StaticText(self.panel_147, wx.ID_ANY, "ppm:  ")
        label_43.SetFont(wx.Font(11, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_134.Add(label_43, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 18)

        self.panel_148 = wx.Panel(self.panel_146, wx.ID_ANY)
        sizer_133.Add(self.panel_148, 1, wx.EXPAND, 0)

        sizer_135 = wx.BoxSizer(wx.VERTICAL)

        self.spin_ctrl_7 = wx.SpinCtrl(self.panel_148, wx.ID_ANY, "100", min=0, max=150, style=wx.ALIGN_RIGHT | wx.SP_ARROW_KEYS)
        self.spin_ctrl_7.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_135.Add(self.spin_ctrl_7, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 17)

        self.panel_149 = wx.Panel(self.panel_146, wx.ID_ANY)
        self.panel_149.SetMinSize((100, 60))
        sizer_133.Add(self.panel_149, 0, wx.EXPAND, 0)

        sizer_136 = wx.BoxSizer(wx.VERTICAL)

        label_44 = wx.StaticText(self.panel_149, wx.ID_ANY, "Uniprot code:  ")
        label_44.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_136.Add(label_44, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 18)

        self.panel_150 = wx.Panel(self.panel_146, wx.ID_ANY)
        sizer_133.Add(self.panel_150, 1, wx.EXPAND, 0)

        sizer_137 = wx.BoxSizer(wx.VERTICAL)

        self.text_ctrl_9 = wx.TextCtrl(self.panel_150, wx.ID_ANY, "Ej. P19121")
        self.text_ctrl_9.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_137.Add(self.text_ctrl_9, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 17)

        self.panel_151 = wx.Panel(self.panel_138, wx.ID_ANY)
        self.panel_151.SetMinSize((-1, 60))
        sizer_120.Add(self.panel_151, 0, wx.EXPAND, 0)

        sizer_138 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_152 = wx.Panel(self.panel_151, wx.ID_ANY)
        self.panel_152.SetMinSize((100, 60))
        sizer_138.Add(self.panel_152, 0, wx.EXPAND, 0)

        sizer_139 = wx.BoxSizer(wx.VERTICAL)

        label_45 = wx.StaticText(self.panel_152, wx.ID_ANY, "Grouping name:  ")
        label_45.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_139.Add(label_45, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 15)

        self.panel_153 = wx.Panel(self.panel_151, wx.ID_ANY)
        sizer_138.Add(self.panel_153, 1, wx.EXPAND, 0)

        sizer_140 = wx.BoxSizer(wx.VERTICAL)

        self.text_ctrl_10 = wx.TextCtrl(self.panel_153, wx.ID_ANY, "Ej. \nMurid albumin (P07724;P02770)")
        self.text_ctrl_10.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_140.Add(self.text_ctrl_10, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 16)

        self.panel_158 = wx.Panel(self.panel_138, wx.ID_ANY)
        self.panel_158.SetMinSize((-1, 60))
        sizer_120.Add(self.panel_158, 0, wx.EXPAND, 0)

        sizer_141 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_163 = wx.Panel(self.panel_158, wx.ID_ANY)
        self.panel_163.SetMinSize((100, 60))
        sizer_141.Add(self.panel_163, 0, wx.EXPAND, 0)

        sizer_147 = wx.BoxSizer(wx.VERTICAL)

        label_48 = wx.StaticText(self.panel_163, wx.ID_ANY, "Sample name:  ")
        label_48.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_147.Add(label_48, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 18)

        self.panel_164 = wx.Panel(self.panel_158, wx.ID_ANY)
        sizer_141.Add(self.panel_164, 1, wx.EXPAND, 0)

        sizer_148 = wx.BoxSizer(wx.VERTICAL)

        self.text_ctrl_13 = wx.TextCtrl(self.panel_164, wx.ID_ANY, "Use specific names")
        self.text_ctrl_13.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_148.Add(self.text_ctrl_13, 1, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 17)

        self.panel_159 = wx.Panel(self.panel_138, wx.ID_ANY)
        sizer_120.Add(self.panel_159, 1, wx.EXPAND, 0)

        self.panel_160 = wx.Panel(self.panel_138, wx.ID_ANY)
        self.panel_160.SetMinSize((-1, 35))
        sizer_120.Add(self.panel_160, 0, wx.EXPAND, 0)

        sizer_144 = wx.BoxSizer(wx.VERTICAL)

        self.button_19 = wx.Button(self.panel_160, wx.ID_ANY, "Run")
        sizer_144.Add(self.button_19, 1, wx.ALIGN_RIGHT | wx.BOTTOM | wx.RIGHT, 4)

        self.panel_160.SetSizer(sizer_144)

        self.panel_164.SetSizer(sizer_148)

        self.panel_163.SetSizer(sizer_147)

        self.panel_158.SetSizer(sizer_141)

        self.panel_153.SetSizer(sizer_140)

        self.panel_152.SetSizer(sizer_139)

        self.panel_151.SetSizer(sizer_138)

        self.panel_150.SetSizer(sizer_137)

        self.panel_149.SetSizer(sizer_136)

        self.panel_148.SetSizer(sizer_135)

        self.panel_147.SetSizer(sizer_134)

        self.panel_146.SetSizer(sizer_133)

        self.panel_145.SetSizer(sizer_132)

        self.panel_144.SetSizer(sizer_131)

        self.panel_143.SetSizer(sizer_130)

        self.panel_142.SetSizer(sizer_129)

        self.panel_141.SetSizer(sizer_128)

        self.panel_140.SetSizer(sizer_127)

        self.panel_139.SetSizer(sizer_126)

        self.panel_138.SetSizer(sizer_120)

        self.panel_119.SetSizer(sizer_107)

        self.panel_121.SetSizer(sizer_109)

        self.panel_120.SetSizer(sizer_108)

        self.panel_115.SetSizer(sizer_104)

        self.panel_114.SetSizer(sizer_111)

        self.panel_113.SetSizer(sizer_110)

        self.panel_112.SetSizer(sizer_103)

        self.panel_111.SetSizer(sizer_102)

        self.panel_110.SetSizer(sizer_101)

        self.panel_109.SetSizer(sizer_100)

        self.panel_108.SetSizer(sizer_99)

        self.panel_107.SetSizer(sizer_98)

        self.panel_106.SetSizer(sizer_97)

        self.panel_105.SetSizer(sizer_96)

        self.panel_104.SetSizer(sizer_95)

        self.panel_103.SetSizer(sizer_94)

        self.panel_102.SetSizer(sizer_93)

        self.panel_101.SetSizer(sizer_92)

        self.panel_100.SetSizer(sizer_91)

        self.panel_99.SetSizer(sizer_90)

        self.panel_98.SetSizer(sizer_89)

        self.panel_97.SetSizer(sizer_88)

        self.panel_96.SetSizer(sizer_87)

        self.panel_95.SetSizer(sizer_86)

        self.panel_94.SetSizer(sizer_85)

        self.panel_93.SetSizer(sizer_84)

        self.panel_92.SetSizer(sizer_83)

        self.panel_91.SetSizer(sizer_82)

        self.panel_90.SetSizer(sizer_81)

        self.panel_69.SetSizer(sizer_80)

        self.notebook_2_pane_2.SetSizer(sizer_79)

        self.panel_157.SetSizer(sizer_119)

        self.panel_130.SetSizer(sizer_118)

        self.panel_129.SetSizer(sizer_117)

        self.panel_128.SetSizer(sizer_116)

        self.panel_137.SetSizer(sizer_125)

        self.panel_136.SetSizer(sizer_124)

        self.panel_135.SetSizer(sizer_123)

        self.panel_134.SetSizer(sizer_122)

        self.panel_133.SetSizer(sizer_121)

        self.panel_127.SetSizer(sizer_115)

        self.panel_126.SetSizer(sizer_114)

        self.panel_125.SetSizer(sizer_113)

        self.panel_124.SetSizer(sizer_112)

        self.panel_118.SetSizer(sizer_106)

        self.panel_117.SetSizer(sizer_105)

        self.panel_70.SetSizer(sizer_59)

        self.panel_68.SetSizer(sizer_57)

        self.panel_76.SetSizer(sizer_76)

        self.panel_87.SetSizer(sizer_78)

        self.panel_85.SetSizer(sizer_77)

        self.panel_67.SetSizer(sizer_75)

        self.panel_84.SetSizer(sizer_74)

        self.panel_83.SetSizer(sizer_73)

        self.panel_82.SetSizer(sizer_72)

        self.panel_81.SetSizer(sizer_71)

        self.panel_66.SetSizer(sizer_70)

        self.panel_80.SetSizer(sizer_69)

        self.panel_79.SetSizer(sizer_68)

        self.panel_78.SetSizer(sizer_67)

        self.panel_77.SetSizer(sizer_66)

        self.panel_65.SetSizer(sizer_65)

        self.panel_75.SetSizer(sizer_64)

        self.panel_74.SetSizer(sizer_63)

        self.panel_64.SetSizer(sizer_17)

        self.panel_73.SetSizer(sizer_62)

        self.panel_72.SetSizer(sizer_61)

        self.panel_63.SetSizer(sizer_13)

        self.panel_71.SetSizer(sizer_60)

        self.panel_59.SetSizer(sizer_56)

        self.panel_61.SetSizer(sizer_12)

        self.panel_60.SetSizer(sizer_58)

        self.panel_62.SetSizer(sizer_55)

        self.notebook_2_pane_1.SetSizer(sizer_54)

        self.panel_58.SetSizer(sizer_53)

        self.panel_57.SetSizer(sizer_52)

        self.panel_56.SetSizer(sizer_51)

        self.panel_55.SetSizer(sizer_50)

        self.panel_15.SetSizer(sizer_11)

        self.panel_8.SetSizer(sizer_10)

        self.panel_7.SetSizer(sizer_9)

        self.notebook_1_pane_2.SetSizer(sizer_3)

        self.panel_53.SetSizer(sizer_49)

        self.panel_54.SetSizer(sizer_48)

        self.panel_52.SetSizer(sizer_47)

        self.panel_51.SetSizer(sizer_46)

        self.panel_50.SetSizer(sizer_45)

        self.panel_44.SetSizer(sizer_38)

        self.panel_41.SetSizer(sizer_36)

        self.panel_23.SetSizer(sizer_35)

        self.panel_22.SetSizer(sizer_34)

        self.panel_21.SetSizer(sizer_33)

        self.panel_14.SetSizer(sizer_32)

        self.panel_5.SetSizer(sizer_31)

        self.panel_31.SetSizer(sizer_16)

        self.panel_30.SetSizer(sizer_14)

        self.panel_39.SetSizer(sizer_30)

        self.panel_38.SetSizer(sizer_29)

        self.panel_29.SetSizer(sizer_28)

        self.panel_37.SetSizer(sizer_27)

        self.panel_36.SetSizer(sizer_26)

        self.panel_28.SetSizer(sizer_25)

        self.panel_35.SetSizer(sizer_24)

        self.panel_34.SetSizer(sizer_23)

        self.panel_27.SetSizer(sizer_22)

        self.panel_33.SetSizer(sizer_21)

        self.panel_32.SetSizer(sizer_20)

        self.panel_26.SetSizer(sizer_19)

        self.panel_25.SetSizer(sizer_18)

        self.panel_13.SetSizer(sizer_15)

        self.panel_4.SetSizer(sizer_8)

        self.panel_12.SetSizer(sizer_7)

        self.panel_3.SetSizer(sizer_6)

        self.panel_2.SetSizer(sizer_5)

        self.notebook_1_pane_1.SetSizer(sizer_2)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade
    def fbbCallback(self, evt):
        pass

# end of class MyFrame
